RegisterCommand("kordinate", function(Igrac)
    local IgracevID = GetPlayerFromServerId(Igrac)
    local PED = GetPlayerPed(IgracevID)
    local Kordinate = GetEntityCoords(PED, true)
    local Heading = GetEntityHeading(PED, true)
    TriggerEvent("chatMessage", "^7[^2UL^7:^2RP^7]", {255, 255, 255}, "X: ".. Kordinate.x .."")
    TriggerEvent("chatMessage", "^7[^2UL^7:^2RP^7]", {255, 255, 255}, "Y: ".. Kordinate.y .."")
    TriggerEvent("chatMessage", "^7[^2UL^7:^2RP^7]", {255, 255, 255}, "Z: ".. Kordinate.z .."")
    TriggerEvent("chatMessage", "^7[^2UL^7:^2RP^7]", {255, 255, 255}, "Heading: ".. Heading .."")
end)